url: "https://gl4uc0m4.github.io/" 
baseurl: "" # the subpath of your site, e.g. /blog
tagline: "Blog dedicated to cybersecuirty and learning."
title: "Gl4uc0m4" # the name of your site, e.g. ACME Corp.
author:
  twitter: Glaucom86060870
description: "Posts about cybersecurity, linux and networks"
repository: "gl4uc0m4/gl4uc0m4.github.io"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-seo-tag

permalink: /:title/
paginate: 4 # amount of posts to show
paginate_path: /page:num/


kramdown:
  parse_block_html: true

search                   : # true, false (default)
search_full_content      : # true, false (default)
search_provider          : # lunr (default), algolia, google
algolia:
  application_id         : # YOUR_APPLICATION_ID
  index_name             : # YOUR_INDEX_NAME
  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : # true (default), false
google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true
twitter_username:  Glaucom86060870
twitter:
  username: Glaucom86060870
  card: summary
logo: /assets/img/masthead.png
social:
  name: Miguel Pantoja
  links:
    - https://github.com/Gl4uc0m4
    - https://twitter.com/Glaucom86060870
    - https://www.linkedin.com/in/miguelpantojaglaucoma/
google_site_verification: uLJmAsL3fzSu_q7n1dmiuHOAbOpq4rQEZfkqHtHutis
